magicBall = [
            'En mi opinión, si',
            'Es cierto',
            'Es decididamente asi',
            'Probablemente',
            'Buen Pronostico',
            'Todo apunta a que si',
            'Sin Duda',
            'Si',
            'Debes confiar en ello',
            'Respuesta vaga, vuelve a intentarlo',
            'Pregunta en otro momento',
            'Sera mejor que no te lo diga ahora',
            'No puedo predecirlo ahora',
            'Concentrate y vuelve a preguntar',
            'No cuentes con ello',
            'Mi respuesta es no',
            'Mis fuentes dicen que no',
            'Las perspectivas no son buenas',
            'Muy dudoso'
            ]
